# Zsh completions
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

    autoload -Uz compinit
    compinit
fi

export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="terminalparty"
ZSH_THEME="esycat"
ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(sudo gnu-utils history tmux ripgrep httpie copydir osx git gradle docker kubectl scala)

source $ZSH/oh-my-zsh.sh

# Common environment variables and command aliases
test -r ~/.envrc && . ~/.envrc
test -r ~/.aliases && . ~/.aliases
test -r ~/.fzf.zsh && . ~/.fzf.zsh

# iTerm integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

