export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="terminalparty"
ZSH_THEME="esycat"
ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(copydir docker git gnu-utils gradle history httpie osx scala sudo)

source $ZSH/oh-my-zsh.sh

# Common environment variables and command aliases
test -r ~/.envrc && . ~/.envrc
test -r ~/.aliases && . ~/.aliases

DOCKER_DEFAULT_MACHINE="dev"
if [ -n "$(docker-machine ls -q --filter name=$DOCKER_DEFAULT_MACHINE --filter state=running)" ] ; then
    eval $(docker-machine env dev)
fi

