#!/usr/bin/env zsh
#
# Authorship check pre-reveive hook for git
#
# @author Eugene Janusov <esycat@gmail.com>
#

FORBIDDEN_COMMITTERS=(unknown root)

committer_name=$($GIT_BIN log -1 --format=format:%cn $newrev)
committer_email=$($GIT_BIN log -1 --format=format:%ce $newrev)

if [ ${FORBIDDEN_COMMITTERS[(i)$committer_name]} -le ${#FORBIDDEN_COMMITTERS} ] ; then
    echo "Commits without proper acknowledgment are not permitted."
    exit 101
fi
