#!/bin/zsh

script_dir=$(dirname `realpath $0`)
. ${script_dir}/.config

while read oldrev newrev refname ; do
    refhead=${refname#refs/heads/}
    # echo $oldrev $newrev $refname $refhead
    source ${script_dir}/authorship
    source ${script_dir}/code-audit
done

if [ $PHP_LINT_RETVAL -ne 0 ] ; then
    echo "Ouch, something's wrong in your PHP conservatory…"
    exit 102
fi

if [ $PUPPET_LINT_LINT_RETVAL -ne 0 ] ; then
    echo "Ouch, your Puppet Force is low, Jedi…"
    exit 103
fi

exit
