package "coreutils"
package "bash-completion"
package "zsh"
package "wget"
package "vim"
package "mc"
package "p7zip-full"
package "realpath"
package "sysstat"
package "dstat"
package "htop"
package "whois"
package "rsync"
package "xpdf"
package "pwgen"
package "git"

if %w{debian}.include?(node.platform_family)
    package "aptitude"
    package "software-properties-common"
    package "python-software-properties"
end
