#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FCNTL_LOCK
setopt NO_HIST_BEEP
setopt PROMPT_SUBST

HISTFILE="$HOME/.history"
HISTSIZE=SAVEHIST=1024

# Load aliases
unalias gls # Prezto's Git module shadows GNU ls utility
unalias gm  # Prezto's Git module shadows GraphicMagick utility
test -r ~/.aliases && . ~/.aliases

# Load Fuzzy Finder
test -r ~/.fzf.zsh && . ~/.fzf.zsh

DOCKER_DEFAULT_MACHINE="devbox"
if [ -n "$(docker-machine ls -q --filter name=$DOCKER_DEFAULT_MACHINE --filter state=running)" ] ; then
    eval $(docker-machine env $DOCKER_DEFAULT_MACHINE)
fi
